# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{knjappserver}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kasper Johansen"]
  s.date = %q{2011-08-03}
  s.description = %q{Which supports a lot of undocumented stuff.}
  s.email = %q{k@spernj.org}
  s.executables = ["check_running.rb", "knjappserver_start.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/check_running.rb",
    "bin/knjappserver_start.rb",
    "lib/conf/README",
    "lib/conf/conf_example.rb",
    "lib/conf/conf_vars_example.rb",
    "lib/files/database_schema.rb",
    "lib/files/run/README",
    "lib/include/class_customio.rb",
    "lib/include/class_erbhandler.rb",
    "lib/include/class_httpresp.rb",
    "lib/include/class_httpserver.rb",
    "lib/include/class_httpsession.rb",
    "lib/include/class_httpsession_knjengine.rb",
    "lib/include/class_httpsession_mongrel.rb",
    "lib/include/class_httpsession_webrick.rb",
    "lib/include/class_knjappserver.rb",
    "lib/include/class_knjappserver_cleaner.rb",
    "lib/include/class_knjappserver_errors.rb",
    "lib/include/class_knjappserver_logging.rb",
    "lib/include/class_knjappserver_mailing.rb",
    "lib/include/class_knjappserver_threadding.rb",
    "lib/include/class_knjappserver_web.rb",
    "lib/include/class_log.rb",
    "lib/include/class_log_access.rb",
    "lib/include/class_log_data.rb",
    "lib/include/class_log_data_link.rb",
    "lib/include/class_log_data_value.rb",
    "lib/include/class_log_link.rb",
    "lib/include/class_session.rb",
    "lib/include/gettext_funcs.rb",
    "lib/include/magic_methods.rb",
    "lib/knjappserver.rb",
    "lib/pages/logs_latest.rhtml",
    "lib/pages/logs_show.rhtml",
    "lib/pages/spec.rhtml",
    "spec/knjappserver_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kaspernj/knjappserver}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A multi-threadded app-web-server.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<knjrbfw>, [">= 0.0.3"])
      s.add_runtime_dependency(%q<erubis>, [">= 0"])
      s.add_runtime_dependency(%q<knjdbrevision>, [">= 0.0.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<knjrbfw>, [">= 0.0.3"])
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<knjdbrevision>, [">= 0.0.2"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<knjrbfw>, [">= 0.0.3"])
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<knjdbrevision>, [">= 0.0.2"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

